In [1]:
x = 100  # enter == goes down one line
y = 200  # enter == goes down one line

x+y   # shift + enter == execute the cell, return the value of the final expression

300

In [2]:
x

100

In [3]:
x+3

103

In [ ]:
# to switch from text-entry mode to command mode, press ESC or click outside the cell
# to switch from command mode to text-entry mode, press RET or click inside the cell

pressing `M` in command mode means that the cell is in Markdown, so you can
*format* **things**

# This is a headline

1. This is the first thing
2. This is the second thing
3. Always show three things, they say
  - one
  - two 
  - three

# Other useful key commands in Jupyter

- a -- creates a new cell *above* the current one
- b -- creates a new cell *below* the current one
- c -- copies the current cell
- x -- cuts the current cell
- v -- pastes the current cell
- z -- undo



In [4]:
# "Magic" commands all start with %

%ls

'Cisco 2020 June 22.ipynb'   airports.zip		 languages.csv
 airlines.dat		     burrito_current.csv	 taxi.csv
 airports/		     celebrity_deaths_2016.csv	 titanic3.csv


In [5]:
%pwd

'/Users/reuven/Consulting/Courses/Data Science/cisco-2020-june'

In [6]:
# Find out about all magic commands with ... %magic
%magic

In [7]:
# The most important magic command we'll use here is %pylab inline

%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [8]:
# import numpy as np    # unnecessary, beacuse we did %pylab inline

In [9]:
np

<module 'numpy' from '/usr/local/lib/python3.8/site-packages/numpy/__init__.py'>

In [14]:
# NumPy provides us with a NumPy n-dimensional array
np.ndarray

numpy.ndarray

In [11]:
int('5')

5

In [12]:
str(1234)

'1234'

In [13]:
list('abcd')

['a', 'b', 'c', 'd']

In [16]:
# don't use np.ndarray to create a NumPy array
# rather, use np.array!

a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [17]:
type(a)

numpy.ndarray

In [18]:
# Method 1 for creating an array: Give np.array a sequence
a = np.array([100, 200, 300, 400, 500])
a

array([100, 200, 300, 400, 500])

In [21]:
# Method 2 for creating an array: Use np.arange
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
np.arange(10)  # from 0 until (not including 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(10, 20)  # from 10 until (not including) 20

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
np.arange(10, 20, 3)  # from 10 until (not including) 20, step size of 3

array([10, 13, 16, 19])

In [26]:
# Method 3 for creating an array: Use np.random.rand(n)
# this returns n random floats from 0-1
a = np.random.rand(5)
a

array([0.21734656, 0.33615391, 0.12789231, 0.78899041, 0.41078495])

In [27]:
# Method 4 for creating an array: Use np.random.randint(min, max, n)

a = np.random.randint(0, 100, 5)
a

array([21, 54, 88,  4, 24])

In [28]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [29]:
# how are arrays like Python lists?
a[2]

30

In [30]:
a[5]

60

In [31]:
# Can I retrieve via a negative index?
a[-1]

100

In [32]:
# They are iterable!
for one_item in a:
    print(one_item, end=' ')

10 20 30 40 50 60 70 80 90 100 

In [33]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [34]:
a[2]

30

In [35]:
a[4]

50

In [36]:
[a[2], a[4]]

[30, 50]

In [37]:
np.array([a[2], a[4]])  # NumPy array with a's index 2 and index 4

array([30, 50])

In [38]:
# fancy indexing
a[ [2,4] ]

array([30, 50])

In [39]:
a[[4,2]]

array([50, 30])

In [40]:
a[[2,2,2,4,4,4]]

array([30, 30, 30, 50, 50, 50])

In [41]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [42]:
# Methods we can call on our NumPy arrays

a.sum()

550

In [43]:
a.mean()  # this will come in handy!

55.0

In [44]:
a.std()  # standard deviation

28.722813232690143

In [45]:
a.min()

10

In [46]:
a.max()

100

In [49]:
a.size  # not a method, but a data attribute -- how long is it?

10

# Exercises with NumPy arrays

1. Create an array with 10 integers of your own choosing.  Retrieve the item at index 3. Retrieve the items at index 5 and 7.  What is the mean of the items at odd indexes?
2. Create an array with 10 random integers from 0-100.  What is the mean?  (Is it 50?)  What is the std?  
3. What if you create an array with 1000 random integers from 0-100?   What is the mean? What is the std?
4. Create an array from 300 to 800, with a step size of 15.  What are the elements at indexes 10, 20, and 30?

# Modes

In command mode, you can switch to/from:

- `m` -- for Markup
- `y` -- for code
- `r` -- for raw text

# Exercises with NumPy arrays

1. Create an array with 10 integers of your own choosing.  Retrieve the item at index 3. Retrieve the items at index 5 and 7.  What is the mean of the items at odd indexes?
2. Create an array with 10 random integers from 0-100.  What is the mean?  (Is it 50?)  What is the std?  
3. What if you create an array with 1000 random integers from 0-100?   What is the mean? What is the std?
4. Create an array from 300 to 800, with a step size of 15.  What are the elements at indexes 10, 20, and 30?

In [50]:
a = np.array([10, 15, 30, 17, 12, -5, 892, 354, 40, 14])
a[3]

17

In [51]:
a[ [5,7] ]

array([ -5, 354])