In [1]:
x = 100  # enter == goes down one line
y = 200  # enter == goes down one line

x+y   # shift + enter == execute the cell, return the value of the final expression

300

In [2]:
x

100

In [3]:
x+3

103

In [ ]:
# to switch from text-entry mode to command mode, press ESC or click outside the cell
# to switch from command mode to text-entry mode, press RET or click inside the cell

pressing `M` in command mode means that the cell is in Markdown, so you can
*format* **things**

# This is a headline

1. This is the first thing
2. This is the second thing
3. Always show three things, they say
  - one
  - two 
  - three

# Other useful key commands in Jupyter

- a -- creates a new cell *above* the current one
- b -- creates a new cell *below* the current one
- c -- copies the current cell
- x -- cuts the current cell
- v -- pastes the current cell
- z -- undo



In [4]:
# "Magic" commands all start with %

%ls

'Cisco 2020 June 22.ipynb'   airports.zip		 languages.csv
 airlines.dat		     burrito_current.csv	 taxi.csv
 airports/		     celebrity_deaths_2016.csv	 titanic3.csv


In [5]:
%pwd

'/Users/reuven/Consulting/Courses/Data Science/cisco-2020-june'

In [6]:
# Find out about all magic commands with ... %magic
%magic

In [7]:
# The most important magic command we'll use here is %pylab inline

%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [8]:
# import numpy as np    # unnecessary, beacuse we did %pylab inline

In [9]:
np

<module 'numpy' from '/usr/local/lib/python3.8/site-packages/numpy/__init__.py'>

In [14]:
# NumPy provides us with a NumPy n-dimensional array
np.ndarray

numpy.ndarray

In [11]:
int('5')

5

In [12]:
str(1234)

'1234'

In [13]:
list('abcd')

['a', 'b', 'c', 'd']

In [16]:
# don't use np.ndarray to create a NumPy array
# rather, use np.array!

a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [17]:
type(a)

numpy.ndarray

In [18]:
# Method 1 for creating an array: Give np.array a sequence
a = np.array([100, 200, 300, 400, 500])
a

array([100, 200, 300, 400, 500])

In [21]:
# Method 2 for creating an array: Use np.arange
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
np.arange(10)  # from 0 until (not including 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(10, 20)  # from 10 until (not including) 20

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
np.arange(10, 20, 3)  # from 10 until (not including) 20, step size of 3

array([10, 13, 16, 19])

In [25]:
# Method 3 for creating an array: Use np.random.rand(n)
# this returns n random floats from 0-1
np.random.rand(5)

array([0.79927932, 0.21889483, 0.67280813, 0.2987091 , 0.96264481])