In [1]:
x = 100  # enter == goes down one line
y = 200  # enter == goes down one line

x+y   # shift + enter == execute the cell, return the value of the final expression

300

In [2]:
x

100

In [3]:
x+3

103

In [ ]:
# to switch from text-entry mode to command mode, press ESC or click outside the cell
# to switch from command mode to text-entry mode, press RET or click inside the cell

pressing `M` in command mode means that the cell is in Markdown, so you can
*format* **things**

# This is a headline

1. This is the first thing
2. This is the second thing
3. Always show three things, they say
  - one
  - two 
  - three

# Other useful key commands in Jupyter

- a -- creates a new cell *above* the current one
- b -- creates a new cell *below* the current one
- c -- copies the current cell
- x -- cuts the current cell
- v -- pastes the current cell
- z -- undo



In [4]:
# "Magic" commands all start with %

%ls

'Cisco 2020 June 22.ipynb'   airports.zip		 languages.csv
 airlines.dat		     burrito_current.csv	 taxi.csv
 airports/		     celebrity_deaths_2016.csv	 titanic3.csv


In [5]:
%pwd

'/Users/reuven/Consulting/Courses/Data Science/cisco-2020-june'

In [6]:
# Find out about all magic commands with ... %magic
%magic

In [7]:
# The most important magic command we'll use here is %pylab inline

%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [8]:
# import numpy as np    # unnecessary, beacuse we did %pylab inline

In [9]:
np

<module 'numpy' from '/usr/local/lib/python3.8/site-packages/numpy/__init__.py'>

In [14]:
# NumPy provides us with a NumPy n-dimensional array
np.ndarray

numpy.ndarray

In [11]:
int('5')

5

In [12]:
str(1234)

'1234'

In [13]:
list('abcd')

['a', 'b', 'c', 'd']

In [16]:
# don't use np.ndarray to create a NumPy array
# rather, use np.array!

a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [17]:
type(a)

numpy.ndarray

In [18]:
# Method 1 for creating an array: Give np.array a sequence
a = np.array([100, 200, 300, 400, 500])
a

array([100, 200, 300, 400, 500])

In [21]:
# Method 2 for creating an array: Use np.arange
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
np.arange(10)  # from 0 until (not including 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(10, 20)  # from 10 until (not including) 20

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
np.arange(10, 20, 3)  # from 10 until (not including) 20, step size of 3

array([10, 13, 16, 19])

In [26]:
# Method 3 for creating an array: Use np.random.rand(n)
# this returns n random floats from 0-1
a = np.random.rand(5)
a

array([0.21734656, 0.33615391, 0.12789231, 0.78899041, 0.41078495])

In [27]:
# Method 4 for creating an array: Use np.random.randint(min, max, n)

a = np.random.randint(0, 100, 5)
a

array([21, 54, 88,  4, 24])

In [28]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [29]:
# how are arrays like Python lists?
a[2]

30

In [30]:
a[5]

60

In [31]:
# Can I retrieve via a negative index?
a[-1]

100

In [32]:
# They are iterable!
for one_item in a:
    print(one_item, end=' ')

10 20 30 40 50 60 70 80 90 100 

In [33]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [34]:
a[2]

30

In [35]:
a[4]

50

In [36]:
[a[2], a[4]]

[30, 50]

In [37]:
np.array([a[2], a[4]])  # NumPy array with a's index 2 and index 4

array([30, 50])

In [38]:
# fancy indexing
a[ [2,4] ]

array([30, 50])

In [39]:
a[[4,2]]

array([50, 30])

In [40]:
a[[2,2,2,4,4,4]]

array([30, 30, 30, 50, 50, 50])

In [41]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [42]:
# Methods we can call on our NumPy arrays

a.sum()

550

In [43]:
a.mean()  # this will come in handy!

55.0

In [44]:
a.std()  # standard deviation

28.722813232690143

In [45]:
a.min()

10

In [46]:
a.max()

100

In [49]:
a.size  # not a method, but a data attribute -- how long is it?

10

# Exercises with NumPy arrays

1. Create an array with 10 integers of your own choosing.  Retrieve the item at index 3. Retrieve the items at index 5 and 7.  What is the mean of the items at odd indexes?
2. Create an array with 10 random integers from 0-100.  What is the mean?  (Is it 50?)  What is the std?  
3. What if you create an array with 1000 random integers from 0-100?   What is the mean? What is the std?
4. Create an array from 300 to 800, with a step size of 15.  What are the elements at indexes 10, 20, and 30?

# Modes

In command mode, you can switch to/from:

- `m` -- for Markup
- `y` -- for code
- `r` -- for raw text

# Exercises with NumPy arrays

1. Create an array with 10 integers of your own choosing.  Retrieve the item at index 3. Retrieve the items at index 5 and 7.  What is the mean of the items at odd indexes?
2. Create an array with 10 random integers from 0-100.  What is the mean?  (Is it 50?)  What is the std?  
3. What if you create an array with 1000 random integers from 0-100?   What is the mean? What is the std?
4. Create an array from 300 to 800, with a step size of 15.  What are the elements at indexes 10, 20, and 30?

In [50]:
a = np.array([10, 15, 30, 17, 12, -5, 892, 354, 40, 14])
a[3]

17

In [51]:
a[ [5,7] ]

array([ -5, 354])

In [52]:
a[[1,3,5,7,9]]

array([ 15,  17,  -5, 354,  14])

In [53]:
a[range(1,10,2)]

array([ 15,  17,  -5, 354,  14])

In [54]:
a = np.random.randint(0, 100, 10)
a

array([24, 37, 47, 36, 38, 83, 33, 26, 18, 81])

In [55]:
a.mean()

42.3

In [56]:
a.std()

21.307510412997573

In [57]:
a = np.random.randint(0, 100, 1000)
a.mean()

49.459

In [58]:
a = np.random.randint(0, 100, 100000)
a.mean()

49.49645

In [59]:
a.std()

28.902134651224294

4. Create an array from 300 to 800, with a step size of 15.  What are the elements at indexes 10, 20, and 30?

In [60]:
a = np.arange(300, 800, 15)
a

array([300, 315, 330, 345, 360, 375, 390, 405, 420, 435, 450, 465, 480,
       495, 510, 525, 540, 555, 570, 585, 600, 615, 630, 645, 660, 675,
       690, 705, 720, 735, 750, 765, 780, 795])

In [61]:
a[10]

450

In [62]:
a[20]

600

In [63]:
a[30]

750

In [64]:
a[[10, 20, 30]]

array([450, 600, 750])

In [65]:
a

array([300, 315, 330, 345, 360, 375, 390, 405, 420, 435, 450, 465, 480,
       495, 510, 525, 540, 555, 570, 585, 600, 615, 630, 645, 660, 675,
       690, 705, 720, 735, 750, 765, 780, 795])

In [67]:
a[1::2]  # start at 1, go until the end, step size of 2

array([315, 345, 375, 405, 435, 465, 495, 525, 555, 585, 615, 645, 675,
       705, 735, 765, 795])

In [68]:
mylist = [10, 20, 30, 40, 50]

mylist + mylist

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [69]:
mylist + 3

TypeError: can only concatenate list (not "int") to list

In [71]:
a = np.array([10, 20, 30, 40, 50])

a+a  # vectorized


array([ 20,  40,  60,  80, 100])

In [72]:
a*a

array([ 100,  400,  900, 1600, 2500])

In [73]:
a/a

array([1., 1., 1., 1., 1.])

In [74]:
a-a

array([0, 0, 0, 0, 0])

In [75]:
a%a

array([0, 0, 0, 0, 0])

In [76]:
b = np.array([100, 200, 300, 400, 500])

a+b

array([110, 220, 330, 440, 550])

In [77]:
c = np.array([1000, 2000])

a+c

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [78]:
a

array([10, 20, 30, 40, 50])

In [79]:
mylist + 3

TypeError: can only concatenate list (not "int") to list

In [81]:
a+3    # broadcasting -- the scalar is "broadcast" across the entire array

array([13, 23, 33, 43, 53])

In [82]:
a-3

array([ 7, 17, 27, 37, 47])

In [83]:
a*3

array([ 30,  60,  90, 120, 150])

In [84]:
a/3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [85]:
a**3

array([  1000,   8000,  27000,  64000, 125000])

In [86]:
a%3

array([1, 2, 0, 1, 2])

In [89]:
np.zeros(5) + 10      # notice, it isn't zeroes!

array([10., 10., 10., 10., 10.])

In [90]:
np.ones(5) * 20

array([20., 20., 20., 20., 20.])

In [91]:
np.random.rand(10)

array([0.40203882, 0.37655816, 0.53829402, 0.54117908, 0.82543581,
       0.65321962, 0.28015683, 0.52806602, 0.41264981, 0.22665215])

In [92]:
# If I want 10 random numbers between 0-100...

np.random.rand(10) * 100

array([91.96768085, 10.21779515, 49.14337761, 16.73090036, 23.86727372,
       55.86886112, 84.5668838 , 19.07293715, 61.98360727, 83.47630904])

In [93]:
a

array([10, 20, 30, 40, 50])

In [94]:
a[3]

40

In [95]:
a[[2,4]]  # fancy indexing

array([30, 50])

In [96]:
# boolean index

a

array([10, 20, 30, 40, 50])

In [97]:
a[2]

30

In [98]:
a[3]

40

In [99]:
a[[2,3]]

array([30, 40])

In [101]:
a[ [True, False, True, False, True] ]   # boolean index or a "mask" index

array([10, 30, 50])

In [102]:
a

array([10, 20, 30, 40, 50])

In [103]:
a + 5

array([15, 25, 35, 45, 55])

In [104]:
a + 30

array([40, 50, 60, 70, 80])

In [105]:
a == 30

array([False, False,  True, False, False])

In [106]:
# mask index applied to a
a[ [False, False,  True, False, False] ]

array([30])

In [107]:
# mask index, a more usual way of creating it:
a[a==30]

array([30])

In [108]:
# mask index for elements <= 30
a[a<=30]

array([10, 20, 30])

# VERY IMPORTANT!  

Boolean indexes are the *main* way to retrieve data from NumPy arrays

In [109]:
# find elements <= mean
a[a <= a.mean()]

array([10, 20, 30])

In [110]:
a = np.random.randint(0, 100, 20)
a

array([83, 91, 74, 69, 50, 81, 99, 67, 61, 63, 12, 35, 16, 76,  9, 31, 77,
       36, 64, 24])

In [111]:
# Let's find the even numbers in a!

# if the result of %2 is 1, the number is odd
# if the result of %2 is 0, the number is even

a%2

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0])

In [112]:
# will this give me the odd elements of a? NO!
a[a%2]

array([91, 91, 83, 91, 83, 91, 91, 91, 91, 91, 83, 91, 83, 83, 91, 91, 91,
       83, 83, 83])

In [113]:
# So, how do I get the odd numbers in a?
a[a%2==1]

array([83, 91, 69, 81, 99, 67, 61, 63, 35,  9, 31, 77])

In [114]:
# So, how do I get the even numbers in a?
a[a%2==0]

array([74, 50, 12, 16, 76, 36, 64, 24])

# Exercise: More with NumPy arrays

1. Generate an array of 20 random ints from 0-100.
2. Find the odd numbers.
3. Find the odd numbers < 20  (you'll probably 2 steps for this, including assigning to a new variable)
4. Find the even numbers between 30 and 70 (you might need 3 steps for this)
5. Get the items at index 1, 3, and 5 for even numbers between 30 and 70 (if there are sufficient examples to give three such numbers).

In [115]:
a = np.random.randint(0, 100, 20)
a

array([91, 99, 60, 23, 77, 51, 77,  6, 92, 50,  5, 74, 33, 34, 94,  9, 63,
       18, 41, 87])

In [118]:
a[a%2==1]

array([91, 99, 23, 77, 51, 77,  5, 33,  9, 63, 41, 87])

In [119]:
b = a[a%2==1]  # all odd numbers from a in b
b[b<20]        # find all numbers < 20 in b

array([5, 9])

In [122]:
# question 4

b = a[a%2==0]  # all even numbers from a are now in b
c = b[b>30]
c = c[c<70]
c

array([60, 50, 34])

In [125]:
c[[1]]

array([50])

In [126]:
a

array([91, 99, 60, 23, 77, 51, 77,  6, 92, 50,  5, 74, 33, 34, 94,  9, 63,
       18, 41, 87])

In [127]:
# I want the even numbers in a < 50

a%2==0 and a<50

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [129]:
x = 100

if x:
    print("It's true-ish")
    
else:
    print("It's false-ish")

It's true-ish


In Python, everything in a boolean context is `True` except for:

- `None`
- `False`
- 0 of any type
- anything empty

In [131]:
x = ''

if x:
    print("It's true-ish")
    
else:
    print("It's false-ish")

It's false-ish


In [134]:
# I want the even numbers in a < 50

# binary and: &
# binary or : |
# binary not: ~  (tilde)

a[(a%2==0) & (a<50)]

array([ 6, 34, 18])

In [ ]:
~(a<50)  # "not" flips the logic -- True->False, False->True

# Exercises with & and |

1. Generate an array of 20 random ints from 0-100.
2. Find the odd numbers < 20
4. Find the even numbers between 30 and 70
5. Find the odd numbers < the array's mean
6. Find the numbers that are \<mean-std or \>mean+std  ("outliers")

In [138]:
a = np.random.randint(0, 100, 20)
a

array([14, 91, 92, 11, 93, 91, 81, 79, 93, 70,  0, 30, 69, 24, 66, 76,  4,
       27, 76, 47])

In [141]:
# 2. Find the odd numbers < 20

a[(a<20) & (a%2==0)]

array([14,  0,  4])

In [145]:
# 4. Find the even numbers between 30 and 70

a[(a%2==0) & (a>30) & (a<70)]

array([66])

In [146]:
# 5. Find the odd numbers < the array's mean

a[(a%2==1) & (a<a.mean())]

array([11, 27, 47])

In [149]:
# 6. Find the numbers that are <mean-std or >mean+std  ("outliers")

a[(a<a.mean()-a.std()) | (a>a.mean()+a.std())]

array([14, 91, 92, 11, 93, 91, 93,  0, 24,  4])

In [150]:
# Python is dynamically typed and strongly typed

# - variables don't have types
# - values do have types

x = 100
type(x)

int

In [151]:
x = 'abcd'
type(x)

str

In [152]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [153]:
a[2] = 31
a

array([10, 20, 31, 40, 50])

In [154]:
a[2] = 123.456

In [155]:
a

array([ 10,  20, 123,  40,  50])

In [156]:
# every NumPy array has a "dtype" (data type)
# every element must be of that type

# when we assign to an array, the assigned value is cast into that type

a

array([ 10,  20, 123,  40,  50])

In [157]:
a.dtype  # get the dtype for a

dtype('int64')

In [158]:
# 64-bit integers can be described in 4 different ways:

np.dtype('int64')  # np + string argument
dtype('int64')     # because we used %pylab inline, which imported the name "dtype"
np.int64           # an attribute of np
int64              # because we used %pylab inline, which imported the name

numpy.int64

In [160]:
a = np.array([10, 20, 30, 40, 50], dtype=np.int8)
a.dtype

dtype('int8')

In [161]:
a

array([10, 20, 30, 40, 50], dtype=int8)

In [162]:
a * 100

array([ -24,  -48,  -72,  -96, -120], dtype=int8)

In [163]:
# 1000, 2000, 3000, 4000, 5000

In [164]:
a ** 5

array([-96,   0, -32,   0,  32], dtype=int8)

In [165]:
a = np.array([10, 20, 30.5, 40, 50])
a

array([10. , 20. , 30.5, 40. , 50. ])

In [166]:
a.dtype

dtype('float64')

In [167]:
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7], dtype=np.float16)

In [168]:
a

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7], dtype=float16)

In [169]:
a+0.1

array([0.2   , 0.2998, 0.4   , 0.5   , 0.6   , 0.7   , 0.8003],
      dtype=float16)

In [170]:
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7], dtype=np.float64)
a+0.1

array([0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8])

In [171]:
a = np.array([10, 20, 30, 40, 50])
a[2] = 123.456

In [172]:
a

array([ 10,  20, 123,  40,  50])

In [173]:
int(123.456)

123

In [174]:
a[2] = '987'

In [175]:
a

array([ 10,  20, 987,  40,  50])

In [176]:
a[2] = 'abcd'

ValueError: invalid literal for int() with base 10: 'abcd'

In [177]:
a

array([ 10,  20, 987,  40,  50])

In [178]:
a.dtype = np.float64  # NEVER EVER EVER DO THIS!

In [179]:
a

array([4.941e-323, 9.881e-323, 4.876e-321, 1.976e-322, 2.470e-322])

In [181]:
a.dtype = np.int64
a

array([ 10,  20, 987,  40,  50])

In [182]:
a.dtype = np.int32

In [183]:
a

array([ 10,   0,  20,   0, 987,   0,  40,   0,  50,   0], dtype=int32)

In [184]:
a.dtype = np.int16
a

array([ 10,   0,   0,   0,  20,   0,   0,   0, 987,   0,   0,   0,  40,
         0,   0,   0,  50,   0,   0,   0], dtype=int16)

In [185]:
a.dtype = np.int64
a

array([ 10,  20, 987,  40,  50])

In [186]:
a

array([ 10,  20, 987,  40,  50])

In [187]:
a.astype(np.float64)  # give me a new NumPy array back, with a dtype of float64 but values from a

array([ 10.,  20., 987.,  40.,  50.])

In [188]:
a = np.array('this is a bunch of words'.split())

In [189]:
a

array(['this', 'is', 'a', 'bunch', 'of', 'words'], dtype='<U5')

In [190]:
a[0] = 'ABCDEFG'
a

array(['ABCDE', 'is', 'a', 'bunch', 'of', 'words'], dtype='<U5')

In [191]:
a = np.array('10 20 30 40 50'.split())
a

array(['10', '20', '30', '40', '50'], dtype='<U2')

In [192]:
a.astype(np.int64)

array([10, 20, 30, 40, 50])

In [193]:
# NumPy arrays are mutable

a = np.array([10, 20, 30, 40, 50, 60])
a[2] = 123
a

array([ 10,  20, 123,  40,  50,  60])

In [194]:
a

array([ 10,  20, 123,  40,  50,  60])

In [195]:
a[[2,3,4]]

array([123,  40,  50])

In [196]:
a[[2,3,4]] = 100
a

array([ 10,  20, 100, 100, 100,  60])

In [197]:
# replace all even elements of a with 234
a[a%2==0] = 234
a

array([234, 234, 234, 234, 234, 234])

# Exercises with NumPy types

1. Create an array of 20 random floats from 0-100.
2. Retrieve those floats whose int portion (i.e., before the .) is even, and calculate their mean.
3. Assign that mean to all of the floats whose int portion (i.e., before .) is odd.
4. Sum all of the numbers > mean.

In [198]:
a = np.random.rand(20)
a

array([0.1947295 , 0.5925425 , 0.85215325, 0.91139211, 0.78227387,
       0.38576936, 0.95780116, 0.15055074, 0.38652898, 0.92918969,
       0.82284713, 0.78725894, 0.99954166, 0.30560708, 0.39914378,
       0.02703077, 0.00785474, 0.34769485, 0.9805817 , 0.72805021])

In [199]:
a = a * 100
a

array([19.47294983, 59.25425023, 85.21532542, 91.13921085, 78.22738718,
       38.57693588, 95.78011641, 15.05507368, 38.65289783, 92.91896912,
       82.28471319, 78.72589435, 99.95416605, 30.56070816, 39.91437817,
        2.70307743,  0.78547355, 34.76948515, 98.0581701 , 72.80502087])

In [200]:
a[a%2 == 0]

array([], dtype=float64)

In [201]:
a%2

array([1.47294983, 1.25425023, 1.21532542, 1.13921085, 0.22738718,
       0.57693588, 1.78011641, 1.05507368, 0.65289783, 0.91896912,
       0.28471319, 0.72589435, 1.95416605, 0.56070816, 1.91437817,
       0.70307743, 0.78547355, 0.76948515, 0.0581701 , 0.80502087])

In [205]:
a[a.astype(np.int64) % 2 == 0]

array([78.22738718, 38.57693588, 38.65289783, 92.91896912, 82.28471319,
       78.72589435, 30.56070816,  2.70307743,  0.78547355, 34.76948515,
       98.0581701 , 72.80502087])

In [207]:
# 2. Retrieve those floats whose int portion (i.e., before the .) 
# is even, and calculate their mean.

a[a.astype(np.int64) % 2 == 0].mean()

54.08906106644634

In [210]:
# 3. Assign that mean to all of the floats whose int portion (i.e., before .) is odd.

a[a.astype(np.int64) % 2 == 1] = a[a.astype(np.int64) % 2 == 0].mean()
a

array([54.08906107, 54.08906107, 54.08906107, 54.08906107, 78.22738718,
       38.57693588, 54.08906107, 54.08906107, 38.65289783, 92.91896912,
       82.28471319, 78.72589435, 54.08906107, 30.56070816, 54.08906107,
        2.70307743,  0.78547355, 34.76948515, 98.0581701 , 72.80502087])

In [213]:
# 4. Sum all of the numbers > mean.
a[a > a.mean()].sum()

935.7326433336337

In [214]:
a = np.random.rand(10) * 100
a

array([55.40327641, 95.98847745, 52.57584037, 12.99173163, 27.85007221,
       24.64890847, 88.33387839, 91.42382158, 47.35707841, 44.19052001])

In [215]:
a / 2

array([27.7016382 , 47.99423872, 26.28792018,  6.49586582, 13.92503611,
       12.32445423, 44.16693919, 45.71191079, 23.67853921, 22.09526001])

In [216]:
a % 2   # divide by 2, and return the remainder

array([1.40327641, 1.98847745, 0.57584037, 0.99173163, 1.85007221,
       0.64890847, 0.33387839, 1.42382158, 1.35707841, 0.19052001])

In [217]:
random.rand(0, 100, 20)

array([], shape=(0, 100, 20), dtype=float64)

In [218]:
test_scores = np.array([90, 95, 87, 92, 96])
test_scores.mean()

92.0

In [219]:
test_scores = np.array([90, 95, 87, 0, 96])
test_scores.mean()

73.6

In [220]:
# np.nan but thanks to %pylab inline, it's also "nan"  (NaN / np.NaN)

test_scores = np.array([90, 95, 87, nan, 96])
test_scores.mean()

nan

In [221]:
type(nan)

float

In [222]:
nan == nan

False

In [223]:
test_scores.sum()

nan

In [225]:
test_scores[test_scores != nan]

array([90., 95., 87., nan, 96.])

In [226]:
# np.isnan -- function that returns True if it sees nan

np.isnan(test_scores)

array([False, False, False,  True, False])

In [227]:
test_scores[np.isnan(test_scores)]

array([nan])

In [228]:
# logical "not" with ~ on NumPy arrays is here to help:

test_scores[~np.isnan(test_scores)]

array([90., 95., 87., 96.])

In [229]:
test_scores[~np.isnan(test_scores)].mean()

92.0

In [230]:
test_scores

array([90., 95., 87., nan, 96.])

In [231]:
# interpolation -- replacing nan values with some other value
# typical to use the mean

# get the non-nan mean
# assign it to the nan values, replacing them

test_scores[np.isnan(test_scores)] = test_scores[~np.isnan(test_scores)].mean()

In [232]:
test_scores

array([90., 95., 87., 92., 96.])

In [233]:
test_scores.mean()

92.0

In [234]:
a = np.array([10, 20, 30, 40, 50])
a[2] = nan

ValueError: cannot convert float NaN to integer

In [235]:
a = a.astype(np.float)
a[2] = nan

a

array([10., 20., nan, 40., 50.])

In [236]:
2**8

256

In [ ]:
# unsigned integer -- it's always positive
# signed integer -- might be neg, might be pos

# 0-255       
# -128 - 127

In [ ]:
# 64 bits = 8 bytes

# 1 billion pieces of data at 64 bits = 1 GB
# 1 billion pieces of data at  8 bits = 128 MB

# 100 billion pieces of data at 64 bits = 100 GB
# 100 billion pieces of data at  8 bits = 12 GB

# Exercise: nan and arrays

1. Create a NumPy array of 30 random ints from 0-1000.
2. Find the numbers that are &lt;mean-std or &gt;mean+std, and set them to be nan
3. Now change those nan values to be the mean of the array's elements.

In [244]:
a = np.random.randint(0, 1000, 30)
a

array([555, 270, 262, 665, 878, 911,  70, 729, 728, 954, 949, 352, 506,
       614, 140, 885, 854, 354, 695, 291, 673, 478, 942, 940, 575, 572,
       386,   6, 708, 299])

In [245]:
a = a.astype(np.float64)
a

array([555., 270., 262., 665., 878., 911.,  70., 729., 728., 954., 949.,
       352., 506., 614., 140., 885., 854., 354., 695., 291., 673., 478.,
       942., 940., 575., 572., 386.,   6., 708., 299.])

In [246]:
a[(a > a.mean()+a.std()) | (a < a.mean()-a.std())] 

array([270., 262., 878., 911.,  70., 954., 949., 140., 885., 854., 291.,
       942., 940.,   6.])

In [247]:
a[(a > a.mean()+a.std()) | (a < a.mean()-a.std())]  = nan

In [248]:
a

array([555.,  nan,  nan, 665.,  nan,  nan,  nan, 729., 728.,  nan,  nan,
       352., 506., 614.,  nan,  nan,  nan, 354., 695.,  nan, 673., 478.,
        nan,  nan, 575., 572., 386.,  nan, 708., 299.])

In [253]:
# get the mean of the non-nan values
# assign that mean to everywhere that we have a nan in a
# a's mean will not move (very much), and none of our values will be nan

a[np.isnan(a)] = a[~np.isnan(a)].mean()

In [254]:
a

array([555.    , 555.5625, 555.5625, 665.    , 555.5625, 555.5625,
       555.5625, 729.    , 728.    , 555.5625, 555.5625, 352.    ,
       506.    , 614.    , 555.5625, 555.5625, 555.5625, 354.    ,
       695.    , 555.5625, 673.    , 478.    , 555.5625, 555.5625,
       575.    , 572.    , 386.    , 555.5625, 708.    , 299.    ])

In [255]:
a.mean()

555.5625

In [256]:
10 / 3  #  truediv

3.3333333333333335

In [257]:
10 // 3   # floordiv

3

In [258]:
# NumPy n-dimensional arrays

type(a)

numpy.ndarray

In [259]:
a = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 100, 110, 120]])
a

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [260]:
a.size

12

In [261]:
len(a)

3

In [262]:
a[0]

array([10, 20, 30, 40])

In [263]:
a[1]

array([50, 60, 70, 80])

In [264]:
a[2]

array([ 90, 100, 110, 120])

In [265]:
a[1][2]  # don't do this!

70

In [266]:
a[1,2]  # this is the NumPy way

70

In [267]:
a

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [268]:
a[[0, 2]]

array([[ 10,  20,  30,  40],
       [ 90, 100, 110, 120]])